- hosts: all

  gather_facts: false
  become: true

  pre_tasks:
    - raw: apt-get -y update && apt-get install -y python-minimal

  tasks:
    - copy:
        src: ./install.sh
        dest: ~/install.sh
